site_name: OptimumDynamics Help
nav:
    - Home: index.md
    - Welcome: welcome.md
    - Getting Started:      
      - Software Requirements: 1_Getting_Started/1_Software_Requirements.md
      - Installation: 1_Getting_Started/2_Installation.md
    - Detailed Guide: 
      - Understanding Vehicle Design: 2_Detailed_Guide/1_Understanding_Vehicle_Design.md
    - Additional Information: 
      - Hot Keys and File Types: 3_Additional_Information/1_Hot_Keys_and_File_Types.md

theme: readthedocs