site_name: OptimumDynamics Help
nav:
    - Home: index.md
    - Welcome: welcome.md
    - Getting Started:
      - Software Requirements: 1_Getting_Started/1_Software_Requirements.md
      - Installation: 1_Getting_Started/2_Installation.md
      - Licensing: 1_Getting_Started/3_Licensing.md
      - Starting a Project: 1_Getting_Started/4_Starting_a_Project.md
    - Detailed Guide:
      - Introduction: 2_Detailed_Guide/0_introduction.md
      - Understanding Vehicle Design: 2_Detailed_Guide/1_Understanding_Vehicle_Design.md
      - Simulation: 2_Detailed_Guide/2_Simulation.md
      - Analysis: 2_Detailed_Guide/3_Analysis.md
      - Output Variable Definitions: 2_Detailed_Guide/4_Output_Variable_Definitions.md
    - Additional Information: 
      - Hot Keys and File Types: 3_Additional_Information/1_Hot_Keys_and_File_Types.md
      - Importing or Exporting Data: 3_Additional_Information/2_Importing_Exporting_Data.md
      - Starting Parameters: 3_Additional_Information/3_Starting_Parameters.md
      - 3D Visualization: 3_Additional_Information/4_3D_Visualization.md
      - FAQ: 3_Additional_Information/5_FAQ.md


theme: 
  name: readthedocs
site_favicon: OptimumDynamics_512x512.ico
