site_name: OptimumDynamics Help File

nav:
    - Home: index.md
    - Welcome: welcome.md
    - Getting Started:
      - Software Requirements: Getting_Started/Software_Requirements.md
      - Installation: Getting_Started/Installation.md
      - Licensing: Getting_Started/Licensing.md
      - Starting a Project: Getting_Started/Starting_a_Project.md
    - Detailed Guide:
      - Introduction: Detailed_Guide/Introduction.md
      - Understanding Vehicle Design: Detailed_Guide/Understanding_Vehicle_Design.md
      - Simulation: Detailed_Guide/Simulation.md
      - Analysis: Detailed_Guide/Analysis.md
      - Output Variable Definitions: Detailed_Guide/Output_Variable_Definitions.md
    - Additional Information: 
      - Hot Keys and File Types: Additional_Information/Hot_Keys_and_File_Types.md
      - Importing or Exporting Data: Additional_Information/Importing_Exporting_Data.md
      - Starting Parameters: Additional_Information/Starting_Parameters.md
      - 3D Visualization: Additional_Information/3D_Visualization.md
      - FAQ: Additional_Information/FAQ.md

theme: 
  name: null
  custom_dir: docs/_theme/mkdocs_windmill_dark
